### ISSUE TITLE
Bug: Issue recebendo label incorretamente

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [Renato66/auto-label#12]
Algumas issues abertas no [qa-brasil/vagas](https://github.com/qa-brasil/vagas) estão recebendo a label _Portugal_, mesmo sem ter essa palavra na issue.

As 2 issues em que vi o problema ocorrer:
1. https://github.com/qa-brasil/vagas/issues/82
2. https://github.com/qa-brasil/vagas/issues/84

Não consegui identificar um padrão que desancadeasse esse problema.

**Comment by Renato66** [comment]
cara.... n faço ideia do que causou isso.... só vou conseguir ter tempo pra olhar no proximo fds

**Comment by PauloGoncalvesBH** [comment]
Nem precisa garrar com isso, porque não voltou a ocorrer e teve impacto muito pequeno. Vou fechar essa issue, se rolar de novo eu notifico aqui.
