### ISSUE TITLE
Feature: Opção de selecionar qual trecho será 'mapeado'

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [Renato66/auto-label#13]
### Sugestão:

Seria interessante ter uma forma de poder definir qual seção pode ser mapeada na hora de inserir label. Com isso a seção `Labels` do repositório [qa-brasil/vagas](https://github.com/qa-brasil/vagas/issues/84) seria melhor aproveitada. Não sendo mais preciso corrigir as labels da issue por causa de palavra no meio da descrição da vaga.

### Problema que motivou essa feature:

Em uma issue de vaga, ela não pede ingês, mas essa empresa tem o diferencial de oferecer curso de inglês. Com isso a label `Inglês` é inserida na vaga.

### Solução:

Será inserida a possibilidade de utilizar `<!-- AUTO-LABEL:START -->` e `<!-- AUTO-LABEL:END -->` na issue.

### Regras:
1. Caso existir `AUTO-LABEL:START` na issue, será mapeado apenas o que está entre `START` e o `END` que está abaixo.
    1. Não existindo, terá o mesmo comportamento de hoje, que é mapear toda a issue.
1. Podem existir _N_ `AUTO-LABEL:START` e `END` na issue. Sempre mapear o que está dentro de todos.

### Comportamento mantido
No exemplo abaixo, seriam inseridas as labels `Bahia`, `Minas Gerais` e `Santa Catarina`.
```
Bahia
Minas Gerais
Santa Catarina
```

### Novo comportamento
No exemplo abaixo, a única label inserida na issue seria `Minas Gerais`.
```
Bahia
<!-- AUTO-LABEL:START -->
Minas Gerais
<!-- AUTO-LABEL:END -->
Santa Catarina
```

No exemplo abaixo, seriam inseridas as labels `Bahia` e `Santa Catarina`.
```
<!-- AUTO-LABEL:START -->
Bahia
<!-- AUTO-LABEL:END -->
Minas Gerais
<!-- AUTO-LABEL:START -->
Santa Catarina
<!-- AUTO-LABEL:END -->
```

### Erros por parte do usuário

O `END` inicial seria desconsiderado porque sempre procura o `START` e o `END` seguinte. A action não quebraria.
No exemplo abaixo, seriam inseridas as labels `Bahia` e `Santa Catarina`.
```
<!-- AUTO-LABEL:END -->
<!-- AUTO-LABEL:START -->
Bahia
<!-- AUTO-LABEL:END -->
Minas Gerais
<!-- AUTO-LABEL:START -->
Santa Catarina
<!-- AUTO-LABEL:END -->
```

 **O item abaixo é interessante analisar como será o comportamento. Exceção é chato de prever.**
❓ **Dúvida:** O melhor seria fazer igual o exemplo anterior, que é ignorar quando não tiver um par de `START` e `END` (nessa ordem), ou emitir exceção igual o exemplo abaixo?

O `START` sem `END` logo abaixo (tem um `START`) quebraria a execução da action. Mostrar uma mensagem clara sobre o erro do uso restrição de trecho.

**Exemplo 1:**
```
<!-- AUTO-LABEL:START -->
<!-- AUTO-LABEL:START -->
Bahia
<!-- AUTO-LABEL:END -->
Minas Gerais
<!-- AUTO-LABEL:START -->
Santa Catarina
<!-- AUTO-LABEL:END -->
```

**Exemplo 2:**
```
<!-- AUTO-LABEL:START -->
Bahia
<!-- AUTO-LABEL:END -->
Minas Gerais
<!-- AUTO-LABEL:START -->
Santa Catarina
<!-- AUTO-LABEL:END -->
<!-- AUTO-LABEL:START -->
```

> _enhancement_

**Comment by dielduarte** [comment]
posso trabalhar nessa @Renato66 ? valeu.

**Comment by Renato66** [comment]
Pode sim man!
