### ISSUE TITLE
Palavra 'aqui' sendo impressa no log de execução da action

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [Renato66/auto-label#17]
Acredito que o código abaixo ficou perdido na implementação:

https://github.com/Renato66/auto-label/blob/3ccbe433d3535c03abbf6922f1a557f6fdf4c02c/src/functions.ts#L35

Gerando o seguinte resultado:

![image](https://user-images.githubusercontent.com/29241659/96505468-89852f00-122c-11eb-9b74-5688818b1c79.png)

Acredito que a seguinte alteração vá servir:

``` diff
- console.log('aqui', elem)
+ console.log(`Label '${elem}' found`)
```

Se concordar abro um PR.

**Comment by Renato66** [comment]
@PauloGoncalvesBH pode abrir um PR man, se vc está participando do hacktoberfest

**Comment by PauloGoncalvesBH** [comment]
Já completei os PRs do hacktoberfest.
@dielduarte gostaria de abrir PR para esse ajuste e aproveitar o hacktoberfest?

**Comment by Renato66** [comment]
closes with #16
