### ISSUE TITLE
Não está colocando label com acento circunflexo

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [Renato66/auto-label#2]
Ao executar o auto-label, ele não está colocando labels com acento.

Versão: 2.1.1

**Exemplo:**
Existem as seguintes labels no repositório e são palavras escritas na issue:
- _Remoto_
- _CLT_
- _Sênior_
- _Especialista_
- São _Paulo_

As únicas labels inseridas foram:
- _Remoto_
- _CLT_
- _Especialista_

Issue aonde o problema ocorreu:
https://github.com/qa-brasil/vagas/issues/39

(Essa issue está com todas as labels, pois eu inseri as faltantes após o build)

**Comment by PauloGoncalvesBH** [comment]
Mais informação que pode apoiar na análise.

Notes que apenas as labels com acento circunflexo não foram adicionadas.

Texto da issue:
![image](https://user-images.githubusercontent.com/29241659/79498316-7a17f580-7fff-11ea-8f62-b623efac3d34.png)

Labels inseridas:
![image](https://user-images.githubusercontent.com/29241659/79498393-9ae04b00-7fff-11ea-8fb1-1c2048f86d60.png)

**Comment by Renato66** [comment]
Fiz os testes e ele consegue acentuar as labels; 
O erro está ao pegar "todas" as labels, estava pegando só as 30 primeiras
vai ser arrumado aqui: #3
