### ISSUE TITLE
auto label with new comments

### ISSUE THREAD

**Issue by Gamemap** [Renato66/auto-label#22]
Hi is it possible to check new comments and auto label with this new comment?

**Comment by Gamemap** [comment]
I found this:

`on:`
`____issue_comment:`
`_________types: [created, edited]`

but it is starting, but does not label exept `default-labels:`

**Comment by Renato66** [comment]
The auto-label can't see changes on new comments, it must be implemented, and I don't think this will be implemented;
It should be a new action with some aditional scope and some options for it

**Comment by Gamemap** [comment]
So the auto-label can't read the new comments?

**Comment by Gamemap** [comment]
So the auto-label can't read the new comments?

**Comment by Gamemap** [comment]
So the auto-label can't read the new comments?

**Comment by Renato66** [comment]
yea... it cant read new comments =/

**Comment by Renato66** [comment]
imagine this:

new issue:
"hey i have found a bug"
auto label adds [bug,triage] label to the issue
mantainer removes the labels: [bug, triage] and added [enhancement]
also he writes:
"hey this is not a bug, its a new feature"
auto label adds [bug] label to the issue

I dont think this is the best way of doing it

**Comment by Gamemap** [comment]
Ok, i understand.

Thank you
Gamemap

**Comment by Gamemap** [comment]
Can you explain me what the `ignore-comments: false` parameter do?

Is it possible to run the auto label if a issue is reopen?
(When runs it with `[edited]` ?)

**Comment by Renato66** [comment]
> Can you explain me what the ignore-comments: false parameter do?
You can leave a list of labels that people can use, and it would'nt be rendered/labeled
```
<!-- labels list:
bug,
triage
warning
 -->
Hey i've found something wrong in this fooBar() function
```
it will render only this text, and woundn't add label any label
```
Hey i've found something wrong in this fooBar() function
```

**Comment by Renato66** [comment]
> Is it possible to run the auto label if a issue is reopen?
i didn't tested it, problably it doesn't
maybe if some refactor it could have this option

**Comment by Gamemap** [comment]
On your website is the option  `opened` , `edited` and `opened and edited`.
What does `edited` do?

**Comment by Renato66** [comment]
> What does edited do?

if you edit some issue the action would be runned again

**Comment by PauloGoncalvesBH** [comment]
> Is it possible to run the auto label if a issue is reopen?

Yes, you can use:

```
on:
  issues:
    types: [reopened]
```

to see more: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues

**Comment by Gamemap** [comment]
It works, but only adds the labels based on the first comment.

**Comment by Gamemap** [comment]
> 
> 
> It works, but only adds the labels based on the first comment.

(Not with a new reopen comment.)
