### ISSUE TITLE
Request: feature to find label on the titles of the issues too

### ISSUE THREAD

**Issue by tjgurwara99** [Renato66/auto-label#24]
https://github.com/Renato66/auto-label/blob/2fc6ce23006cea59b7b23ce7f4c70e4e233de49f/src/main.ts#L20

Could you consider adding support for parsing the issue title too.

I think it is an easy fix, just append `const isssueTitleLabel: []string = getIssueLabels(issue.title, repoLabels)` and concatenate both to get it.

Do you think it is worth doing that or is it not useful? I say this because title tags like `feat` `bug` are used a lot in issues of big projects and it would be worth adding it I think.

**Comment by Renato66** [comment]
Hey, man that is usefull :D

It might be on the next release

**Comment by tjgurwara99** [comment]
> It might be on the next release

Let me know when its released (by closing this issue or updating it). Also let me know if I can help with anything!!😄

**Comment by dgteixeira** [comment]
hey @Renato66 , was this already released?
Thanks!
We are currently using https://github.com/github/issue-labeler, but if you apply this, we'll probably change to yours :)

**Comment by Renato66** [comment]
hey guys
@tjgurwara99, @dgteixeira

it's included and working in v3.1.0 as default title and body will be scrapped to find labels,

on #91 (aka 3.2.0) will be available in the docs to ignore it
