### ISSUE TITLE
labels-synonyms criando e inserindo label errada

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [Renato66/auto-label#7]
No meu projeto fiz a seguinte configuração:
`labels-synonyms: '{"Inglês":["inglês","english"]}'`

Pelo que li na documentação, ele deveria procurar as palavras `inglês`  e `english` na issue, encontrando alguma ia adicionar a label `Inglês`.

Porém ao executar a pipeline ele adicionou a label `English`, que não existia no repositório.

Com isso, parece que o comportamento do sinônimos não está como o esperado e não poderia criar label, já que apenas adiciona o que já existe no projeto.

Issue com esse problema: https://github.com/qa-brasil/vagas/issues/49

- error

**Comment by Renato66** [comment]
Verificarei neste final de semena :)
