### ISSUE TITLE
not only Eng support

### ISSUE THREAD

**Issue by smir-ant** [Renato66/auto-label#89]
i want use it with russian lang, \w is only eng, what about all symbols instead 0-9!@#... or [а-я][a-z]?

(not \w in parse)

**Comment by Renato66** [comment]
Hey @smir-ant, can you provide an simple use case so I can run some test around here?

when you say `\w` is on this function?
https://github.com/Renato66/auto-label/blob/5fc2b8531da05745b6b0477ac9bd323de1547dc3/src/scraper/text.ts#L44

**Comment by smir-ant** [comment]
@Renato66  oh, sry
yeap, about case:

if the issue markdown has labelsSynonyms, then there is no problem. as long as we're not talking about Russian symbols.

for example, if "2/5" is specified in labelsSynonyms: ["плохо"], then the label was not set, however, if the trigger is "bad" instead "плохо", then the label is put down as it should be

if I'm not mistaken... of course, since I tried to use it a week ago and have completely forgotten :(

**Comment by PauloGoncalvesBH** [comment]
@Renato66, doing this change will support the Russian symbols and anyone that uses Unicode characters:

```diff
- (?<label>(\s*\w.+|\n)*?)\s*
+ (?<label>(\s*\p{L}.+|\n)*?)\s*
```

## \w

Matches any alphanumeric character (A-Z, a-z, 0-9) and the underscore (_).

## \p{L}

It uses the Unicode property to match any letter from any alphabet. This includes all uppercase and lowercase letters from all alphabets recognized by Unicode (Latin, Cyrillic, Greek, Arabic, Hebrew, etc.).

> Needs review

**Comment by Renato66** [comment]
@smir-ant  and @PauloGoncalvesBH, just refactored the code to implement the same logic but without the regex, now everything is ok at @v3.1.0 or @v3
