### ISSUE TITLE
Unable to add same synonym to different labels

### ISSUE THREAD

**Issue by SGI-CAPP-AT2** [Renato66/auto-label#93]
```json
{
  "labelsSynonyms": {
    "dependencies": ["dependabot", "dependency", "dependencies"],
    "security": ["security"],
    "ui/ux": ["layout", "screen", "design", "figma"],
    "good first issue": ["dependabot", "dependency", "dependencies", "ui/ux"] 
  },
  "defaultLabels": ["unapproved"]
}
```
as shown in above `auto-label.json5` config I want to have two labels assigned to issue `"good first issue"` and `"dependencies"` but it only adds good first issuse
see following issues:
https://github.com/SGI-CAPP-AT2/talawa-admin/issues/13
https://github.com/SGI-CAPP-AT2/talawa-admin/issues/14

**Comment by Renato66** [comment]
@SGI-CAPP-AT2 going to take some time to look at it in the following days
